### ISSUE TITLE
Dark Theme Inconsistency: Search Bar Color Reverts to Light Mode During Sidebar Navigation

### ISSUE THREAD

**Issue by SouhailKrs** [facebook/stylex#149]
**The problem**

While using the [Stylexjs.com](https://stylexjs.com/) dark theme, an unexpected color inconsistency arises when navigating through the sidebar, causing the search bar to switch to light mode colors.
Interestingly, the color behavior normalizes when toggling between light and dark modes again. However, the issue resurfaces upon navigating the sidebar once more.

![issue](https://github.com/facebook/stylex/assets/61523279/7b36ba0f-3cac-478f-83f0-fe49fa494bc3)

**Steps to reproduce:**
1. Enable StyleX dark theme.
2. Consistently navigate through the sidebar.
3. Observe the search bar switching to light mode colors.

**Expected behavior**

I anticipated the search bar to maintain a consistent appearance with dark theme colors throughout the sidebar navigation.

**Environment**
- Browsers Tested: [Brave, Opera, Edge]

**Comment by purohitdheeraj** [comment]
I can work on this , have already started

**Comment by nmn** [comment]
Yes, this is a known issue. @purohitdheeraj happy to accept a PR if you can fix this. However, this is a bug in Docusaurus itself. Upgrading Docusaurus breaks a bunch of things, which is why we've been stuck with this.

I'm working with the maintainer of Docusaurus to investigate if we can add support for StyleX to Docusaurus 3 and then migrate to it.

**Comment by purohitdheeraj** [comment]
thanks @nmn actually the styles for dark theme are not applied for search panel, so simply we can use that 4-5 css variables in :root of custom css and its working fine , just raised a PR
