### ISSUE TITLE
Interoperatibility with React Native for Web

### ISSUE THREAD

**Issue by steida** [facebook/stylex#280]
I would like to use StylexX with React Native for the Web. I know RNfW has its own styling, but I don't use it because I want StyleX, and I do not plan to make a native version of my app. The reason why I want to use RNfW is its excellent API for mouse, keyboard, and touch, so I'm using only Pressable.

With the previous StyleX version, I used this workaround:

```ts
// To use external styling.
// https://github.com/necolas/react-native-web/releases/tag/0.18.0
const reactNativeStyles = StyleSheet.create({
  pressable: {
    $$css: true,
    pressable: stylex.props(styles.pressable).className,
  },
});
```

This workaround isn't working anymore. Any idea how to style RNfW components? cc @necolas

**Comment by steida** [comment]
OK, it still works, but the specificity is different 🤔 Anyway, is it a recommendation, or should we not use StyleX with RNfW together?

**Comment by nmn** [comment]
@steida Don't use StyleX with RNW like that. StyleX now has features so that it can work even when you import `StyleSheet`. So you should be able to configure StyleX to work RNW's API.

Add this to the configuration, and the StyleX compiler will compile `StyleSheet` as if it was `stylex`.

```
importSources: {from: 'react-native', as: 'StyleSheet'}
```

I think @necolas plans to do this in RNW itself soon.

**Comment by steida** [comment]
Until Necolas shows us how to do it, the approach I'm using now is to use StylexX styles directly with the RNfW style. It works except for specificity, so I have to use important:

```ts
// eslint-disable-next-line @stylexjs/valid-styles
alignItems: "center !important",
```

Also, this is RNfW styles provider:

```ts
const StylesProvider: FC<{ children: React.ReactNode }> = ({ children }) => {
  useServerInsertedHTML(() => {
    // @ts-expect-error RNfW
    // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment, @typescript-eslint/no-unsafe-call
    const sheet = StyleSheet.getSheet();
    return (
      <style
        // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment, @typescript-eslint/no-unsafe-member-access
        dangerouslySetInnerHTML={{ __html: sheet.textContent }}
        // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment, @typescript-eslint/no-unsafe-member-access
        id={sheet.id}
      />
    );
  });
  return children;
};
```

I wish I knew how to use it properly, anyway...

**Comment by nmn** [comment]
I would suggest waiting for a month or two.

**Comment by necolas** [comment]
> StyleX now has features so that it can work even when you import StyleSheet.

This won't work because `StyleSheet.props` is not a function interally. I could make a change to align with the StyleX API but even that wouldn't be enough because internally the library doesn't import from `react-native`, and it has several other expectations that can't be met yet.

> It works except for specificity...

What does this mean specifically? What is the specificity issue?

> the approach I'm using now is to use StylexX styles directly with the RNfW style

You can't safely use StyleX in RNfW at the moment, as it would be mixing RNfW's internal styling mechanism with a completely separate system. There were also a number of features missing from StyleX that prevent it from RNfW using it as a drop-in replacement for `StyleSheet`. Some of these may have been fixed, but most remain:

* Compiler doesn't enforce what `StyleSheet` currently does, e.g., it allows arbitrary selectors.
* Compiler allows unsafe shorthand properties that aren't part of the RN API.
* Compiler doesn't vendor prefix CSS.
* Compiler doesn't polyfill certain properties or values, e.g., `pointerEvents` values of `box-none` and `box-only`.
* I don't have a clear idea of how to integrate the StyleX Types.
* Regresses runtime layout performance, because 1) you can't define CSS resets, and 2) there was aggressive shorthand expansion creating too many class names. I think solving (1) is also a challenge because exposing a public API for that in StyleX would likely be abused.
* StyleX doesn't polyfill LTR/RTL switching for older browsers.
* The StyleX style injector doesn't manage style sheet ordering as well as RNfW, which regresses dev-time perf and correctness.

You might think "but I'm only targeting web", but the biggest user of RNfW is Expo and I can't regress their apps.

**Comment by nmn** [comment]
I'll create an issue to tackle all the issues blocking RNW adoption and follow-up. Thanks for the list @necolas

**Comment by necolas** [comment]
@nmn One idea I have is that I could try to first make sure StyleSheet generates CSS class names that what we get from StyleX (probably pretty close since we use the same hash function), and then when we run the RNfW unit tests using StyleX instead, it should be easier to spot if the rendered results have unexpectedly changed. If we can match existing behavior, that's probably good enough to get started on the transition even if things like "arbitrary selectors" can't be prevented - since most xplat customers will not be able to use those anyway if running on RN too.

**Comment by nmn** [comment]
That sounds like a great idea!

> even if things like "arbitrary selectors" can't be prevented

This is actually fairly easy to prevent. I just didn't get to it aiming for a full parser-based validation. We can ship something simple quickly.

**Comment by necolas** [comment]
Our solution for using StyleX on native is now open source: https://github.com/facebook/react-strict-dom

**Comment by steida** [comment]
@necolas Thank you! Does it work with React Native for the Web or replace it?

**Comment by nmn** [comment]
@steida The project is still early, but it is designed to be used separately from RNW.
