### ISSUE TITLE
programatically create a theme

### ISSUE THREAD

**Issue by conarwelsh** [facebook/stylex#281]
**The problem**

Firstly, not sure if this is a bug or a feature so i apologize if this is in the wrong place.
Per the comment [here]( https://github.com/facebook/stylex/issues/122#issuecomment-1849801726) I would like to basically have a dark theme, a light theme, and a default theme that responds to the media query for dark mode.  However I was hoping to have a single source of truth for the 3 themes.  Basically I wanted to programmatically create the light and dark themes from the base vars.  However it is not creating the theme correctly with the classNames being `UnknownFile__dark`.

With this setup you would be easily able to maintain the 3 themes, and you could simply use the `setTheme("dark" | "light" | null)` to toggle between dark, light, and the system media queries.

Is this because the variables are not defined in this exact file?  Is there a way around this?

The base theme is working perfectly fine with this example, the only problem being that the dark and light themes effectively do nothing when applied which is expected considering the theme output.

**How to reproduce**

The code below should put together a working sample:

tokens.stylex.js
```js
export const colorTokens = {
  primaryText: {
    default: DARK_TEXT,
    [DARK]: LIGHT_TEXT,
  },
  primaryTextInverted: {
    default: LIGHT_TEXT,
    [DARK]: DARK_TEXT,
  },
  secondaryText: {
    default: "#c6c6c6",
    [DARK]: "#c6c6c6",
  },
  secondaryTextInverted: {
    default: "#c6c6c6",
    [DARK]: "#c6c6c6",
  },
  lightText: LIGHT_TEXT,
  darkText: DARK_TEXT,
  surface1: {
    default: "#ffffff",
    [DARK]: "#121212",
  },
  surface2: {
    default: "#c6c6c6",
    [DARK]: "#282828",
  },
  surface3: {
    default: "#5e5e5e",
    [DARK]: "#3f3f3f",
  },
  surface4: {
    default: "#303030",
    [DARK]: "#575757",
  },
  border: {
    default: "#121212",
    [DARK]: "#ffffff",
  },
  primary: "#04b1fb",
  primary1: "#1d8bc3",
  primary2: "#21668f",
  primary3: "#1e445d",
  primary4: "#152530",
  secondary: "#3f7f85",
  secondary1: "#346469",
  secondary2: "#2a4b4e",
  secondary3: "#1f3335",
  secondary4: "#141d1e",
  info: "#388cfa",
  warning: "#cc8800",
  success: "#009f42",
  error: "#b41c2b",
}

export const colors = stylex.defineVars(colorTokens)
```
lightAndDark.js
```js
import { createTheme } from "@stylexjs/stylex"
import { colorTokens, colors } from "../tokens.stylex"

const DARK = "@media (prefers-color-scheme: dark)"

const darkTheme = {}
const lightTheme = {}

Object.keys(colorTokens).map((key) => {
  if (colorTokens[key][DARK]) {
    darkTheme[key] = colorTokens[key][DARK]
    lightTheme[key] = colorTokens[key].default
  } else {
    darkTheme[key] = colorTokens[key]
    lightTheme[key] = colorTokens[key]
  }
})

console.log(darkTheme)
console.log(lightTheme)

export const dark = createTheme(colors, darkTheme)
export const light = createTheme(colors, lightTheme)

console.log(dark)
console.log(light)
```
ThemeProvider.js
```js
export const ThemeContext = createContext(null)

export default function ThemeProvider({ children }) {
  const [theme, setTheme] = useState(null)
  const themes = { dark, light }

  return (
    <ThemeContext.Provider value={[theme, setTheme]}>
      <div {...stylex.props(themes[theme], styles.base)}>{children}</div>
    </ThemeContext.Provider>
  )
}
```
Example `console.log` output from code above
```
lightAndDark.js:19 {primaryText: '#ffffff', primaryTextInverted: '#121212', secondaryText: '#c6c6c6', secondaryTextInverted: '#c6c6c6', lightText: '#ffffff', …}

lightAndDark.js:20 {primaryText: '#121212', primaryTextInverted: '#ffffff', secondaryText: '#c6c6c6', secondaryTextInverted: '#c6c6c6', lightText: '#ffffff', …}

lightAndDark.js:25 {$$css: true, var(--xacle5s): 'xph554m', UnknownFile__dark: 'UnknownFile__dark'}

lightAndDark.js:26 {$$css: true, var(--xacle5s): 'xph554m', UnknownFile__light: 'UnknownFile__light'}
```

**Expected behavior**

I was hoping for the themes to successfully be created programmatically.

**Environment (include versions). Did this work in previous versions?**

**Comment by nmn** [comment]
This is not allowed. All styles need to be statically defined as constants. The compiler can track simple expressions but not if you mutate objects like this.

```tsx
Object.keys(colorTokens).map((key) => {
  if (colorTokens[key][DARK]) {
    darkTheme[key] = colorTokens[key][DARK]
    lightTheme[key] = colorTokens[key].default
  } else {
    darkTheme[key] = colorTokens[key]
    lightTheme[key] = colorTokens[key]
  }
})
```

Also `defineVars` is a map of keys to variable names, you can't do this anyway!

--------

Your problem would be solved by being able to define themes in the same file as the `defineVars` call. This is not currently supported, but we can think about it.

For now, the best solution is to define a third "theme" instead of relying on the theme:

```tsx
// tokens.stylex.js

// define obviously wrong colors by default
// So you immediately catch a mistake where a theme isn't applied
export const colors = stylex.defineVars({
  primary: "lime",
  primary1: "lime",
  primary2: "lime",
  primary3: "lime",
  primary4: "lime",
  secondary: "lime",
  secondary1: "lime",
  secondary2: "lime",
  secondary3: "lime",
  secondary4: "lime",
  info: "lime",
  warning: "lime",
  success: "lime",
  error: "lime",
});
```

```tsx
// lightAndDark

import { createTheme } from "@stylexjs/stylex"
import { colorTokens, colors } from "../tokens.stylex"

const darkColors = {
  primary: 'black',
  ...
};
const lightColors = {
  primary: 'white',
  ...
}

const DARK = "@media (prefers-color-scheme: dark)";

export const dark = createTheme(colors, darkColors);
export const light = createTheme(colors, lightColors);
export const auto = createTheme(colors, {
  primary: {
    default: lightColors.primary,
    [DARK]: darkColors.primary,
  },
  ...
});
```

**Comment by conarwelsh** [comment]
This is great I can definitely make this work. I didn't think about doing it that way. Thanks for the quick response!

**Comment by olivierpascal** [comment]
> Your problem would be solved by being able to define themes in the same file as the defineVars call. This is not currently supported, but we can think about it.

I think it would solve my case too.

I cannot use your solution @nmn because I want to be able to show both light and dark mode in the same page. Light mode is the default, and dark mode is set by applying a darkColorRoles theme to a parent div.

The issue is the following: for a component to use dark colors, I need to reapply the component theme at the component level.

The workaround you proposed is interesting (see https://github.com/facebook/stylex/issues/162#issuecomment-1853775396)

```ts
import React from 'react';
import { colorScheme } from './colorScheme.stylex';
import { myComponentVars } from './myComponentVars.stylex';

const theme = stylex.createTheme(colorScheme, {
  primary: 'green',
});
const componentTheme = stylex.createTheme(myComponentVars, {
  text: colorScheme.primary,
});

const styles = stylex.create({
  container: {
    color: colorScheme.primary, // <- theme is applied (output green)
    color: myComponentVars.text, // <- theme is not applied (output red)
  },
});

export const MyComponent = () => <div {...stylex.props(styles.container, theme, componentTheme)}>TEXT</div>;
```

The problem is that `myComponentVars` (imported from `./myComponentVars.stylex`) contains a lot of vars in my case.

Naturally I don't want to have to redefine by copy/pasting the entire var object (`{ text: colorScheme.primary }` in your example) to create the `componentTheme`.

And from my understanding, there is no way to share the var object to reapply it in a more smooth way.

For the moment, I use `createTheme` in the same file as the `defineVars` call (with a shared object for both calls), it works but it introduces undesirable side effects.

**Comment by olivierpascal** [comment]
@nmn I'm afraid it won't solve my specific issue, which requires:

1. both light and dark theme to be both displayed on the same page

<img width="307" alt="image" src="https://github.com/facebook/stylex/assets/2182039/cbfa2eee-6039-4b28-8328-e4419b70f91e">

2. color scheme could be overridden by the user

`@media (prefers-color-scheme: dark)` will only depend of the OS settings, and cannot be overridden locally.

**Comment by necolas** [comment]
Yeah it's actually 'auto', 'light', 'dark' (and potentially other schemes like 'high-contrast', which use a different media query). When you define vars, the default is conventionally 'light' and 'dark' is the "alternate". Using the vars directly without 'createTheme' produces the 'auto' behaviour. Manually forcing light or dark can only be done on specific trees, but we don't have a mechanism for that anymore and also cannot use the "default" theme within the context of another theme. My original proposal for the theming APIs accounted for these use cases but worked via a prop on a component that allowed you to pick the "displayMode" of a theme (ie the theme alternate).

We probably need to modify "createTheme" to return multiple values, one for each alternate. And might want to revert the media query syntax for assigning alternate values like "dark". It would also be great to not require all values to be reassigned when creating themes from the same tokens

**Comment by nmn** [comment]
@olivierpascal What I'm proposing would actually solve your needs.

To clarify:
- The "default" or "auto" theme is a theme that defines the default values defined in `defineVars` as a "theme" that can applied explicitly. This will let you change to custom theme on a sub-tree and then "go back" to the default for a child sub-tree.
- The "light" theme is a theme with all the light-mode colors applied without checking a media query
- The "dark" theme is a theme with all the dark-mode colors applied without checking a media query

These "themes" are the same as the themes created with `createTheme` so you can apply them on particular UI sub-trees to only affect the colors within those sub-trees.

-----

All of what I'm describing is already possible today as well. My proposal would only reduce the amount of boilerplate needed.

Here's a simple example with two colors:

Start by defining the variables:
```tsx
// tokens.stylex.ts
import * as stylex from '@stylexjs/stylex';

const DARK = '@media (prefers-color-scheme: dark)';
export const tokens = stylex.defineVars({
  bg: {default: 'white', [DARK]: '#222'},
  primary: {default: 'black', [DARK]: 'white'},
});
```
Now you have defined some variables which default to the "auto" theme.

Next, you can define the three themes you need explicitly:

```tsx
// tokens.stylex.ts
import * as stylex from '@stylexjs/stylex';
import {tokens} from './tokens.stylex';

const DARK = '@media (prefers-color-scheme: dark)';
export const autoTheme = stylex.createTheme(tokens, {
  bg: {default: 'white', [DARK]: '#222'},
  primary: {default: 'black', [DARK]: 'white'},
});
export const lightTheme = stylex.createTheme(tokens, {
  bg: 'white',
  primary: 'black',
});
export const darkTheme = stylex.createTheme(tokens, {
  bg: '#222',
  primary: 'white',
});
```

Now you have all three themes that you can use for different sub-trees of your UI:

```tsx
<div>
   <Card>This is going to use the default values of variables so be in the "auto" theme</Card>
  <div {...stylex.props(lightTheme)}>
     <Card>This is going to always use the "light" theme</Card>
  </div>
  <div {...stylex.props(darkTheme)}>
     <Card>This is going to always use the "dark" theme</Card>
     <div {...stylex.props(autoTheme)}>
       <Card> This card is reset to use the  "auto" theme</Card>
    </div>
  </div>
</diV
```

- both light and dark theme are displayed on the same page
- color scheme can be overridden by the user: You can apply the `lightTheme` or `darkTheme` conditionally.

-----

Again, all of this is possible today. My proposal would just reduce boilerplate.

**Comment by olivierpascal** [comment]
@nmn 

I've take some time to try to illustrate the issue in a reproducible repo:

https://github.com/olivierpascal/stylex-issue

I really hope this will be clearer now.

Tokens are used to define global color roles `surface` and `onSurface`.

Test1 component is using directly global color roles in stylex.create().

Test2 and Test3 components are defining local tokens that uses global color roles, like:

```ts
import * as stylex from '@stylexjs/stylex';
import { colorRoles } from '../theme/colorRoles.stylex';

export const componentTokens = stylex.defineVars({
  container: colorRoles.surface,
  text: colorRoles.onSurface,
});
```

Test3 works with https://github.com/facebook/stylex/issues/162#issuecomment-1853775396 but introduces new issues, which makes component-level theming not possible due to the need to re-assign new local values with createTheme() in the component (see Test3.tsx:15).

<img width="1015" alt="image" src="https://github.com/facebook/stylex/assets/2182039/3b340ab4-7946-40ef-aac8-4152782a0f44">

**Comment by olivierpascal** [comment]
@nmn I would be glad if you had some spare time to take a look on this usecase 🙏🏼🙏🏼

**Comment by nmn** [comment]
@olivierpascal Looking at the discussion on #162 I now know the issue you're describing. I'll take it from the top with all my comments:

## This pattern leads to bloat

The pattern that you're using in Test2 and Test3 should be avoided. By creating groups of variables specific to each component you're making it impossible to share styles with other components. This will lead to CSS bloat. You should simply accept conditions or styles as a prop.

## You can merge themes

If you need to use this pattern anyway, what you're doing in `Test3.tsx` as a workaround to use the current values of `colorRoles` can work just fine. You can still accept a `Theme<typeof tokens>` as a prop and apply it after your own `componentTheme` to allow users of the component to override the theme. 

The one caveat here is that only the last used `Theme` is applied so users of your component would need to create themes where all keys have been set explicitly.

There is even a way around this caveat by accepting styles that set variables.

```tsx
const stylesForTheme = stylex.create({
  valid: {
    [tokens.container]: 'red',
    [tokens.text]: 'blue',
  },
});
```

It is not easy to validate this with types right now, but we don't recommend this pattern anyway.

## This is how CSS works

Finally, I want to again let you know that this is how CSS variables work. They are values that get their value when they are being set. They are not reactive signals that resolve their value when they are being read. This is also how React Context which also provides simple values.

The behaviour you want is simply impossible to achieve consistently with CSS today. It'll become possible to achieve in the future when `@scope` and Style queries are available across all browsers, but even then it's not always the expected behaviour.
