### ISSUE TITLE
Documentation and examples how to setup stylex with a stencil.js project

### ISSUE THREAD

**Issue by lehmamic** [facebook/stylex#381]
### Describe the feature request

It would be nice to have documentation and an example how to setup stylex with a stencil.js project.

**Comment by nmn** [comment]
You're welcome to try setting up a new Stenciljs+StyleX project, and we will link to it on our new "ecosystem" page.

Here's the basics to help you get started:

1. You must *NOT* use shadow DOM: Shadow DOM is inherently incompatible with atomic CSS and forces styles to be loaded for each component.
2. If you're using StencilJS with JSX, the rest of the usage should be pretty much the same as React or Solid.

Here's a simple example:

```tsx
import { Component, Prop, h } from '@stencil/core';
import * as stylex from '@stylexjs/stylex';
import { format } from '../../utils/utils';

@Component({
  tag: 'my-component',
  styleUrl: 'my-component.css',
  shadow: false, // IMPORTANT
})
export class MyComponent {
  @Prop() first: string;
  @Prop() middle: string;
  @Prop() last: string;

  private getText(): string {
    return format(this.first, this.middle, this.last);
  }

  render() {
    return <div {...stylex.attrs(styles.text)}>Hello, World! I'm {this.getText()}</div>;
  }
}

const styles = stylex.create({
  text: { color: 'red', },
});
```

The new `stylex.attrs` function returns an object with `class` instead of `className` but otherwise works like `stylex.props`.

**Comment by lehmamic** [comment]
Thanks for the answer
