### ISSUE TITLE
Docuemntation on writing composable component libraries. 

### ISSUE THREAD

**Issue by pnegahdar** [facebook/stylex#403]
Stylex is really cool, very much enjoying it so far. Thanks!

I was wondering if the team could write a small doc on how to write components effectively and any helpful patterns you've all discovered internally.

Some design questions I'm considering:

1) Overriding the `style` prop or using a different prop like `stylex` prop for passing styles to the component.

2) What is the best-practice component interface?

What I wrote is something like: 

```tsx
// would be nice if the one that includes undefined is exported too (the argument to style.props) 
export type StyleXStyle = StyleXArray<(null | undefined | CompiledStyles) | boolean | Readonly<[CompiledStyles, InlineStyles]>>
export type StyleXStyles = ReadonlyArray<StyleXStyle> | StyleXStyle

export interface StyleProp {
    style?: StyleXStyles
}
export type StyledFC<PropType> = React.FC<Omit<PropType, "style"> & StyleProp>
```

Which lets me use a `<Div/>` type 

```tsx
export const Div: StyledFC<React.DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>> = ({ style, ...props }) => {
    return <div {...props} {...stylex.props(style)} />
}

const Component = () => {
    return <Div style={styles.mainContainer}/>
}
```

3) Best way to deal with styling nested components -- though this is generally a problem in react. Is this the best way? 

```tsx
interface Props {
    style?: StyleXStyle
    innerContainerStyle?: StyleXStyle   
}
```

Any helpful tips or docs on best-practices for sharable composable libraries through your learnings would be great!

**Comment by necolas** [comment]
Yes I like those ideas. Scattered throughout our replies there is some info about component libraries - it's a good subject for us to bring to the docs.

About your design questions:

1. I like using just the `style` prop as React Native has been doing. It helps standardise component styles. Originally, `stylex(styles)` returned only a `className` string, so engineers had to use `style` for dynamic styles. internally we have components with both `style` and `xstyle` (for passing StyleX objects) props. That's less ergonomic and results in inconsistencies between how "styles" work depending on which prop you use. StyleX now owns both the `className` and `style` props, so we only need 1 prop to have better economics and results.
2. We actually have a library that does something very similar, but instead of `<Div>` and `stylex.create` we have `<html.div>` and `css.create`. It also includes experimental support for running on React Native.
3. Yes that's a common pattern and easy to reason about.

Let us know of any more questions you have. Naman has a lot of experience working with our component library team and might have some thoughts on good patterns

**Comment by nmn** [comment]
The patterns themselves are consistent with what we have used in the examples in our docs. Just to try and summarise the patterns we try to follow, we:
- use the `style` prop to pass override styles into a component.
  - When a component, say `<Dialog>` needs to accept styles for multiple sub-parts, it can accept multiple props that end with `Style`:
    - `containerStyle`, `triggerStyle`,`closeBtnStyle` etc.
- Any styles accepted as props should be applied last in the `stylex.props` call.
- Instead of creating a helper type like `StyledFC`, it makes sense to just add keys typed `StyleXStyles` to the usual `Props` type definitions. IMO, this is easier to read and introduces one less abstraction for developers to learn about.

As @necolas mentioned we're working on a library that uses the pattern of using `style` prop with `<html.div>`. I'm also working on a complementary Babel plugin which can be used alongside StyleX to make this pattern compile to `{...stylex.props()}` for you.

**Comment by pnegahdar** [comment]
Great thanks! I'll close this issue. As an aside request it seems generally helpful to export the argument type of `style.props` for these sorts of derivative libraries.

**Comment by nmn** [comment]
@pnegahdar The types are already exported if you know where to look for them!

**Comment by necolas** [comment]
Our solution for using StyleX on native is now open source: https://github.com/facebook/react-strict-dom

**Comment by pnegahdar** [comment]
> @pnegahdar The types are already exported if you know where to look for them!

Please do share and point me in the right direction. 

I see this in my d.ts file for the arguments to `stylex.props`: 

```
type IStyleX = {
  (
    ...styles: ReadonlyArray<
      StyleXArray<(null | undefined | CompiledStyles) | boolean>
    >
  ): string;
  props: (
    this: null | undefined | unknown,
    ...styles: ReadonlyArray<
      StyleXArray<
        | (null | undefined | CompiledStyles)
        | boolean
        | Readonly<[CompiledStyles, InlineStyles]>
      >
    >
  ) => 
```

The closes thing I see is `StyleXStyles` which is: 

```
export type StyleXStyles<
  CSS extends UserAuthoredStyles = CSSPropertiesWithExtras,
> = StyleXArray<
  | null
  | false
  | GenStylePropType<CSS>
  | Readonly<[GenStylePropType<CSS>, InlineStyles]>
>;
export type StyleXStylesWithout<CSS extends UserAuthoredStyles> = StyleXStyles<
  Omit<CSSPropertiesWithExtras, keyof CSS>
>;
```

Which doesn't include a `undefined` which is pretty clutch for conditional styles. I guess we could infer them from the `stylex.props`.


@necolas thanks for sharing, will check it out.

**Comment by nmn** [comment]
```tsx
import * as types from '@stylexjs/stylex/lib/StyleXTypes'
```
