### ISSUE TITLE
hover, active and focus designs should not display on disabled buttons?

### ISSUE THREAD

**Issue by tilnea** [facebook/stylex#793]
### Describe the issue

I need to add `:not(:disabled)` selectors in my styles, otherwise the disabled button still gets the hover, active and focus styled on it.

```tsx
border: {
  default: `2px solid ${theme.primary}`,
  ":disabled": `2px solid ${theme.disabled}`,
  ":focus:not(:disabled)": `2px solid ${theme.focus}`,
  ":active:not(:disabled)": `2px solid ${theme.focus}`,
  ":hover:not(:disabled)": `2px solid ${theme.primaryHover}`,
},
```

### Expected behavior

only show disabled styled on disabled buttons (and other elements)

```tsx
border: {
  default: `2px solid ${theme.primary}`,
  ":disabled": `2px solid ${theme.disabled}`,
  ":focus": `2px solid ${theme.focus}`,
  ":active": `2px solid ${theme.focus}`,
  ":hover": `2px solid ${theme.primaryHover}`,
},
```

### Steps to reproduce

```json
"react": "^18.3.1"
"@stylexjs/stylex": "^0.9.3"
```
    
1. Add border styles above on a button
2. Check the behavior on a disabled button

**Comment by nmn** [comment]
`:disabled` is highly discouraged in StyleX. Unlike `:hover`, `:focus` and `:active`, the `:disabled` pseudo class is dependent on you as a developer setting a `disabled` attribute.

So the recommended pattern is to apply styles conditionally instead of using `:disabled`.

----

Rationale: In order to generate the smallest possible CSS file, we generate styles for all pseudo classes in a single, pre-defined order. Therefore `:active` always has a higher specificity than `:hover` for example. 

With somthing like `:disabled` there is no one "correct" way to decide how it should be ordered.
