### ISSUE TITLE
How to creating a <Box /> component.

### ISSUE THREAD

**Issue by taylorpreston** [facebook/stylex#811]
### Describe the feature request

I would love if there was some documentation on how to create a <Box /> component that are often at the root of design systems if it is possible.

We want 0 runtime css with a props driven component api like this. 
`<Box p={{base: 0,  md: "14" }>Hello World</Box>`

**Comment by zaydek** [comment]
@taylorpreston I actually went through a thought evolution like this, but where I ended up is not as generalizable as you're imagining. Instead, if I find myself repeating the same properties over and over again, I can make it a component that accepts the style arguments as component arguments like `<Row gap={...}>` and I can extend it with arbitrary styles like `<Row _styles={...} gap={...}>`. Instead of exposing all possible CSS properties to `<Row>`, I only expose the most relevant ones. And still, `<Row>` can be arbitrarily extended using `_styles`.

My overall realization is that a `<Box>` component is that if it can do too many things, it won't do any one thing well. In general, I heavily rely on StyleX's stylesheet API. I've come to really enjoy it, but every now and then it's good to have general layout components.

Furthermore, the `Sx.createComponent` is somewhat similar to Styled Components but a little different. The idea is you first declare your styles like you would in StyleX, then, if you need to, you can quickly wrap them up as components that accept style arguments like `<Text textAlign="center">` instead of `<Text _styles={styles.textAlignCenter}>`. I try to solve the 80% use case and just use the stylesheet API for everything else. I find they work really well together.

I don't have enough time to explain how it works right now, but I'll paste some relevant code. If this sparks any interest, just let me know.

https://gist.github.com/zaydek/9dd8746abd26dce5d0044fb329f7e079

**Comment by nmn** [comment]
@taylorpreston A generic `Box` component can be created but what is not supported is the configuration on a per-breakpoint basis.

This often becomes an anti-pattern when trying to implement responsive layouts. Your design system should include a set of "values". Those values should change based on the viewport breakpoints internally. You should not be mixing and matching arbitrary values for different viewport breakpoints.

So, I would recommend something like the following instead:

```tsx
<Box p="sm_fixed">Hello World</Box>
<Box p="sm"_scaling>Hello World</Box>
```

```tsx
function Box({p, ...props}) {
  return <div 
    {...stylex.props(styles.base, paddingStyles[p])}
    {...props}
  />;
}

const styles = styles.create({
  base: {boxSizing: 'border-box'},
});

const TABLET = '@media (min-width: 768px) and (max-width: 1279.9px)';
const DESKTOP = '@media (min-width: 1280px)';

const paddingStyles = stylex.create({
  sm_fixed: {padding: 4},
  sm_scaling: {
    padding: {
      default: 4,
      [TABLET]: 8,
      [DESKTOP]: 16,
    },
  },
  md_fixed: {padding: 8},
  ...
});
```

Basically, you should have an opinion about which values belong together ahead of time in your design system. 

For example, `sm_scaling` above is `4px`, `8px` and `16px` on different breakpoints. This is guaranteed to be consistent. Allowing arbitrary values is error prone and it becomes easier to accidentally forget to provide a value for a certain breakpoint or to not be consistent with the design on how those values fit together.

I think a more locked down design system with named values such as `sm` are preferrable, but you *can* allow a larger set of value combinations if you prefer as well:

```tsx
const paddingStyles = stylex.create({
  '2': {padding: 2},
  '2-4-8': {
    padding: {
      default: 2,
      [TABLET]: 4,
      [DESKTOP]: 8,
    },
  },
  '4': {padding: 4},
  '4-8-16': {
    padding: {
      default: 4,
      [TABLET]: 8,
      [DESKTOP]: 16,
    },
  },
  ...
});
```

This approach is less prescriptive but it still gives you a consolidated place to see all the way the values may be used together and let's the `Box` component ensure consistency.
